package model;


// Generated 07/05/2018 20:44:06 by Hibernate Tools 4.3.1



/**
 * Assunto generated by hbm2java
 */
public class Assunto  implements java.io.Serializable {


     private Integer codigo;
     private Disciplina disciplina;
     private Flashcard flashcard;
     private String tema;

    public Assunto() {
    }

    public Assunto(Disciplina disciplina, Flashcard flashcard, String tema) {
       this.disciplina = disciplina;
       this.flashcard = flashcard;
       this.tema = tema;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Disciplina getDisciplina() {
        return this.disciplina;
    }
    
    public void setDisciplina(Disciplina disciplina) {
        this.disciplina = disciplina;
    }
    public Flashcard getFlashcard() {
        return this.flashcard;
    }
    
    public void setFlashcard(Flashcard flashcard) {
        this.flashcard = flashcard;
    }
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }




}


