package model;


// Generated 07/05/2018 20:44:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cronograma generated by hbm2java
 */
public class Cronograma  implements java.io.Serializable {


     private Integer codigo;
     private Usuario usuario;
     private String inicio;
     private String fim;
     private Set<Disciplina> disciplinas = new HashSet<Disciplina>(0);
     private Set<Executado> executados = new HashSet<Executado>(0);

    public Cronograma() {
    }

	
    public Cronograma(Usuario usuario, String inicio, String fim) {
        this.usuario = usuario;
        this.inicio = inicio;
        this.fim = fim;
    }
    public Cronograma(Usuario usuario, String inicio, String fim, Set<Disciplina> disciplinas, Set<Executado> executados) {
       this.usuario = usuario;
       this.inicio = inicio;
       this.fim = fim;
       this.disciplinas = disciplinas;
       this.executados = executados;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getInicio() {
        return this.inicio;
    }
    
    public void setInicio(String inicio) {
        this.inicio = inicio;
    }
    public String getFim() {
        return this.fim;
    }
    
    public void setFim(String fim) {
        this.fim = fim;
    }
    public Set<Disciplina> getDisciplinas() {
        return this.disciplinas;
    }
    
    public void setDisciplinas(Set<Disciplina> disciplinas) {
        this.disciplinas = disciplinas;
    }
    public Set<Executado> getExecutados() {
        return this.executados;
    }
    
    public void setExecutados(Set<Executado> executados) {
        this.executados = executados;
    }




}


