package model;


// Generated 07/05/2018 20:44:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Disciplina generated by hbm2java
 */
public class Disciplina  implements java.io.Serializable {


     private Integer codigo;
     private Cronograma cronograma;
     private String nome;
     private Set<Executado> executados = new HashSet<Executado>(0);
     private Set<Assunto> assuntos = new HashSet<Assunto>(0);

    public Disciplina() {
    }

	
    public Disciplina(Cronograma cronograma, String nome) {
        this.cronograma = cronograma;
        this.nome = nome;
    }
    public Disciplina(Cronograma cronograma, String nome, Set<Executado> executados, Set<Assunto> assuntos) {
       this.cronograma = cronograma;
       this.nome = nome;
       this.executados = executados;
       this.assuntos = assuntos;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Cronograma getCronograma() {
        return this.cronograma;
    }
    
    public void setCronograma(Cronograma cronograma) {
        this.cronograma = cronograma;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Executado> getExecutados() {
        return this.executados;
    }
    
    public void setExecutados(Set<Executado> executados) {
        this.executados = executados;
    }
    public Set<Assunto> getAssuntos() {
        return this.assuntos;
    }
    
    public void setAssuntos(Set<Assunto> assuntos) {
        this.assuntos = assuntos;
    }




}


