package model;


// Generated 07/05/2018 20:44:06 by Hibernate Tools 4.3.1



/**
 * Executado generated by hbm2java
 */
public class Executado  implements java.io.Serializable {


     private ExecutadoId id;
     private Cronograma cronograma;
     private Disciplina disciplina;
     private Horario horario;

    public Executado() {
    }

    public Executado(ExecutadoId id, Cronograma cronograma, Disciplina disciplina, Horario horario) {
       this.id = id;
       this.cronograma = cronograma;
       this.disciplina = disciplina;
       this.horario = horario;
    }
   
    public ExecutadoId getId() {
        return this.id;
    }
    
    public void setId(ExecutadoId id) {
        this.id = id;
    }
    public Cronograma getCronograma() {
        return this.cronograma;
    }
    
    public void setCronograma(Cronograma cronograma) {
        this.cronograma = cronograma;
    }
    public Disciplina getDisciplina() {
        return this.disciplina;
    }
    
    public void setDisciplina(Disciplina disciplina) {
        this.disciplina = disciplina;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }




}


