package model;


// Generated 07/05/2018 20:44:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pasta generated by hbm2java
 */
public class Pasta  implements java.io.Serializable {


     private Integer codigo;
     private Usuario usuario;
     private String nome;
     private Set<Flashcard> flashcards = new HashSet<Flashcard>(0);

    public Pasta() {
    }

	
    public Pasta(Usuario usuario, String nome) {
        this.usuario = usuario;
        this.nome = nome;
    }
    public Pasta(Usuario usuario, String nome, Set<Flashcard> flashcards) {
       this.usuario = usuario;
       this.nome = nome;
       this.flashcards = flashcards;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Flashcard> getFlashcards() {
        return this.flashcards;
    }
    
    public void setFlashcards(Set<Flashcard> flashcards) {
        this.flashcards = flashcards;
    }




}


